In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset=pd.read_csv('iris_csv.csv')
dataset.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
x=dataset.iloc[:,:4]
x.head()

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [5]:
y=dataset.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [9]:
y_pred=classifier.predict(x_test)

In [10]:
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [11]:
y_test

110     Iris-virginica
84     Iris-versicolor
52     Iris-versicolor
93     Iris-versicolor
109     Iris-virginica
100     Iris-virginica
140     Iris-virginica
129     Iris-virginica
122     Iris-virginica
69     Iris-versicolor
89     Iris-versicolor
42         Iris-setosa
106     Iris-virginica
34         Iris-setosa
98     Iris-versicolor
95     Iris-versicolor
86     Iris-versicolor
46         Iris-setosa
99     Iris-versicolor
50     Iris-versicolor
27         Iris-setosa
80     Iris-versicolor
72     Iris-versicolor
54     Iris-versicolor
11         Iris-setosa
135     Iris-virginica
61     Iris-versicolor
148     Iris-virginica
22         Iris-setosa
18         Iris-setosa
Name: class, dtype: object

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 7  0  0]
 [ 0 13  1]
 [ 0  2  7]]


In [13]:
print(accuracy_score(y_test,y_pred))

0.9


In [ ]:
from sklearn import tree
tree.plot