In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [67]:
dataset=pd.read_csv('iris_csv.csv')

In [68]:
x=dataset.iloc[:,:4]
x.head()

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [70]:
y=dataset.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [72]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [73]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [74]:
y_pred=classifier.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa'], dtype=object)

In [75]:
y_test

98     Iris-versicolor
80     Iris-versicolor
43         Iris-setosa
41         Iris-setosa
42         Iris-setosa
131     Iris-virginica
46         Iris-setosa
74     Iris-versicolor
53     Iris-versicolor
34         Iris-setosa
133     Iris-virginica
121     Iris-virginica
55     Iris-versicolor
132     Iris-virginica
120     Iris-virginica
71     Iris-versicolor
52     Iris-versicolor
21         Iris-setosa
47         Iris-setosa
31         Iris-setosa
135     Iris-virginica
11         Iris-setosa
100     Iris-virginica
94     Iris-versicolor
17         Iris-setosa
12         Iris-setosa
40         Iris-setosa
123     Iris-virginica
105     Iris-virginica
27         Iris-setosa
Name: class, dtype: object

In [77]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))


[[13  0  0]
 [ 0  8  0]
 [ 0  1  8]]


In [78]:
print(accuracy_score(y_test,y_pred))

0.9666666666666667


In [79]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.89      1.00      0.94         8
 Iris-virginica       1.00      0.89      0.94         9

       accuracy                           0.97        30
      macro avg       0.96      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30

