In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot


In [2]:
dataset=pd.read_csv('iris_csv.csv')

In [3]:
dataset.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [5]:
x=dataset.iloc[:,:4]
x.head()

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [6]:
y=dataset.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [8]:
x_train.head()

sepallength  sepalwidth  petallength  petalwidth
140          6.7         3.1          5.6         2.4
61           5.9         3.0          4.2         1.5
42           4.4         3.2          1.3         0.2
108          6.7         2.5          5.8         1.8
12           4.8         3.0          1.4         0.1

In [9]:
y_train.head()

140     Iris-virginica
61     Iris-versicolor
42         Iris-setosa
108     Iris-virginica
12         Iris-setosa
Name: class, dtype: object

In [10]:
x_test.head()

sepallength  sepalwidth  petallength  petalwidth
82           5.8         2.7          3.9         1.2
109          7.2         3.6          6.1         2.5
80           5.5         2.4          3.8         1.1
23           5.1         3.3          1.7         0.5
46           5.1         3.8          1.6         0.2

In [11]:
y_test.head()

82     Iris-versicolor
109     Iris-virginica
80     Iris-versicolor
23         Iris-setosa
46         Iris-setosa
Name: class, dtype: object

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [14]:
y_pred=classifier.predict(x_test)
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor'], dtype='<U15')

In [15]:
y_test

82     Iris-versicolor
109     Iris-virginica
80     Iris-versicolor
23         Iris-setosa
46         Iris-setosa
68     Iris-versicolor
123     Iris-virginica
36         Iris-setosa
15         Iris-setosa
125     Iris-virginica
122     Iris-virginica
98     Iris-versicolor
51     Iris-versicolor
111     Iris-virginica
84     Iris-versicolor
78     Iris-versicolor
65     Iris-versicolor
10         Iris-setosa
102     Iris-virginica
85     Iris-versicolor
27         Iris-setosa
21         Iris-setosa
77     Iris-versicolor
64     Iris-versicolor
100     Iris-virginica
131     Iris-virginica
87     Iris-versicolor
14         Iris-setosa
62     Iris-versicolor
73     Iris-versicolor
Name: class, dtype: object

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))


[[ 8  0  0]
 [ 0 13  1]
 [ 0  0  8]]
0.9666666666666667
