import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('iris_csv.csv')

In [3]:
dataset.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
x=dataset.iloc[:,:-4]
y=dataset.iloc[:,-1]

In [5]:
x.head()


sepallength
0          5.1
1          4.9
2          4.7
3          4.6
4          5.0

In [6]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [9]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear')

In [10]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [11]:
y_pred=classifier.predict(x_test)

In [12]:
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [13]:
y_test

124     Iris-virginica
22         Iris-setosa
18         Iris-setosa
96     Iris-versicolor
44         Iris-setosa
115     Iris-virginica
33         Iris-setosa
2          Iris-setosa
53     Iris-versicolor
102     Iris-virginica
104     Iris-virginica
32         Iris-setosa
25         Iris-setosa
39         Iris-setosa
85     Iris-versicolor
125     Iris-virginica
145     Iris-virginica
13         Iris-setosa
66     Iris-versicolor
89     Iris-versicolor
142     Iris-virginica
7          Iris-setosa
117     Iris-virginica
60     Iris-versicolor
35         Iris-setosa
63     Iris-versicolor
90     Iris-versicolor
67     Iris-versicolor
119     Iris-virginica
140     Iris-virginica
Name: class, dtype: object

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))

[[9 2 0]
 [1 8 0]
 [0 2 8]]


In [15]:
print(accuracy_score(y_test,y_pred))

0.8333333333333334
